name: Java CI

on:
  push:
  pull_request:
  schedule:
    - cron: '30 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8, 11]

    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn -B clean package

      - name: Filter artifacts
        run: |
          mkdir artifact
          cp target/*.jar artifact

      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts-java${{ matrix.java }}
          path: artifact
